#https://github.com/eugenp/tutorials/tree/master/spring-5-reactive-oauth
spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: fooClientIdPassword
            client-secret: secret
            scope: read,foo
            authorization-grant-type: authorization_code
            redirect-uri-template: http://localhost:8089/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8080/spring-security-oauth-server/oauth/authorize
            token-uri: http://localhost:8080/spring-security-oauth-server/oauth/token
            user-info-uri: http://localhost:8088/spring-security-oauth-resource/users/extra
            user-name-attribute: user_name
server:
  port: 8089
