spring:
  security:
    oauth2:
      client:
        registration:
          bael:
            client-name: bael
            client-id: fooClientIdPassword
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          bael:
            token-uri: http://localhost:8080/spring-security-oauth-server/oauth/token

server:
  port: 8089